# Generated by Django 5.2.5 on 2026-02-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_alter_skill_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileskill',
            name='desired_exchange_skills',
            field=models.ManyToManyField(blank=True, help_text='Skills the user specifically wants in exchange for teaching this skill.', related_name='wanted_in_exchange_for', to='skills.skill'),
        ),
    ]
