# Generated by Django 5.2.5 on 2026-01-28 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mettings', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='review_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='tokens_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='mettings.booking')),
            ],
        ),
    ]
