# Generated by Django 5.2.5 on 2026-01-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mettings', '0010_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='admin_action_message',
            field=models.TextField(blank=True, help_text='Type a message here to send to the reporter upon saving.', null=True),
        ),
    ]
