# Generated by Django 5.2.5 on 2026-02-02 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_experience_points_profile_level'),
        ('mettings', '0011_report_admin_action_message'),
        ('skills', '0004_alter_skill_skill_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_swaps', to='accounts.profile')),
                ('requester_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_as_offered', to='skills.skill')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_swaps', to='accounts.profile')),
                ('target_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_as_target', to='skills.skill')),
            ],
        ),
    ]
