# Generated by Django 5.2.5 on 2026-02-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mettings', '0012_swaprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='times_taught_incremented',
            field=models.BooleanField(default=False),
        ),
    ]
