# Generated by Django 5.2.5 on 2026-02-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mettings', '0013_booking_times_taught_incremented'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_joined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='requester_joined',
            field=models.BooleanField(default=False),
        ),
    ]
