# Generated by Django 5.2.5 on 2026-02-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mettings', '0014_booking_actual_start_time_booking_provider_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tokens_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
