# Generated by Django 5.2.5 on 2026-01-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('earned', 'Earned'), ('spent', 'Spent'), ('purchased', 'Purchased'), ('refund', 'Refund')], max_length=10),
        ),
    ]
