# Generated by Django 5.2.5 on 2026-01-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
