# Generated by Django 5.2.5 on 2026-02-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_experience_points_profile_level'),
        ('skills', '0004_alter_skill_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='desired_skills',
            field=models.ManyToManyField(blank=True, related_name='wanted_by_profiles', to='skills.skill'),
        ),
    ]
