# Generated by Django 5.2.5 on 2026-02-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_profile_desired_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_reviewed_platform',
            field=models.BooleanField(default=False),
        ),
    ]
