# Generated by Django 5.2.5 on 2026-02-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_profile_has_reviewed_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_level_up_modal',
            field=models.BooleanField(default=False),
        ),
    ]
