# Generated by Django 5.2.5 on 2026-02-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_profile_show_level_up_modal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
