# Generated by Django 5.2.5 on 2026-02-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_profile_experience_level_and_more'),
        ('accounts', '0022_profile_blocked_until'),
    ]

    operations = [
    ]
