# Generated by Django 5.2.5 on 2026-02-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_merge_20260206_1640'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='profile',
                    name='verified',
                    field=models.BooleanField(default=True),
                ),
            ],
            database_operations=[],
        ),
    ]
