# Generated by Django 5.2.5 on 2026-02-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_profile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('earned', 'Earned'), ('spent', 'Spent'), ('purchased', 'Purchased'), ('refund', 'Refund'), ('bonus', 'Bonus')], max_length=10),
        ),
    ]
