"""
Django settings for skilllink project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
import cloudinary
import cloudinary.uploader
import cloudinary.api
import dj_database_url
import os
import socket

# -----------------------------------------------------------------------------
# IPv4 CONNECTION PATCH
# Fixing [Errno 101] Network is unreachable on Railway (which prefers IPv6 but blocks it)
# -----------------------------------------------------------------------------
try:
    # Save original getaddrinfo just in case
    _original_getaddrinfo = socket.getaddrinfo

    def new_getaddrinfo(*args, **kwargs):
        # Force family to AF_INET (IPv4)
        if args and args[0] in ['smtp.gmail.com', 'www.googleapis.com', 'accounts.google.com']:
            # Only force for Google services to be safe, or everywhere?
            # Let's force everywhere to be safe on this host.
            responses = _original_getaddrinfo(*args, **kwargs)
            return [r for r in responses if r[0] == socket.AF_INET]
            
        return _original_getaddrinfo(*args, **kwargs)

    # Apply the patch GLOBALLY
    socket.getaddrinfo = new_getaddrinfo
    print("✅ Applied IPv4 Network Patch for SMTP")
except Exception as e:
    print(f"⚠️ Failed to apply IPv4 patch: {e}")

# DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"


CLOUDINARY_URL = config('CLOUDINARY_URL')







# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&7f1um-rj65ryxq666sl&8r-6z-1sckm$kjbvwm#$711dnyxbr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)


# Host/Domain names that this Django site can serve
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "0.0.0.0",
    "skill-link-ptzd.onrender.com",
    "skill-link-production-f36b.up.railway.app",
]




# Security settings - disabled for local development

# SECURE_SSL_REDIRECT = False
# SESSION_COOKIE_SECURE = False
# CSRF_COOKIE_SECURE = False
# SECURE_BROWSER_XSS_FILTER = False
# SECURE_CONTENT_TYPE_NOSNIFF = False
# SECURE_PROXY_SSL_HEADER = None

# Fly.io Security Configuration
# if config('FLY_APP_NAME', default=None):
#     SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
#     csrftrum = f"https://{config('FLY_APP_NAME')}.fly.dev"
#     CSRF_TRUSTED_ORIGINS = [csrftrum]
#     SESSION_COOKIE_SECURE = True
#     CSRF_COOKIE_SECURE = True

# Railway Security Configuration
if config('RAILWAY_ENVIRONMENT', default=None):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    CSRF_TRUSTED_ORIGINS = [
        "https://skill-link-production-f36b.up.railway.app",
        f"https://{config('RAILWAY_PUBLIC_DOMAIN', default='skill-link-production-f36b.up.railway.app')}"
    ]
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Render Security Configuration
# if config('RENDER', default=False, cast=bool):
#     SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
#     CSRF_TRUSTED_ORIGINS = ["https://skill-link-ptzd.onrender.com"]
#     SESSION_COOKIE_SECURE = True
#     CSRF_COOKIE_SECURE = True



# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig',
    'home',
    'mettings',
    'payement',
    'skills',
    "channels",
    'django_crontab',
    "cloudinary",
    "cloudinary_storage",
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'skilllink.middleware.TimezoneMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'skilllink.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR , 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.tz',
            ],
        },
    },
]

WSGI_APPLICATION = 'skilllink.wsgi.application'
ASGI_APPLICATION = "skilllink.asgi.application"

# Channels Configuration
# Default to InMemory in dev if no REDIS_HOST is set, but keeping flexibility
# For strict local dev without Redis:
# if config('REDIS_URL', default=None):
#     CHANNEL_LAYERS = {
#         "default": {
#             "BACKEND": "channels_redis.core.RedisChannelLayer",
# Channel Layers for WebSockets
# Use Redis if REDIS_URL is provided (production), else fallback to InMemory for local dev
REDIS_URL = config("REDIS_URL", default=None)

if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

import dj_database_url
DATABASES = {
    'default': dj_database_url.parse(
        'postgresql://neondb_owner:npg_p1BHbFMZcz2q@ep-curly-union-a1iec63p-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require',
        conn_max_age=45,
        ssl_require=True,
    )
}

DATABASES['default']['CONN_HEALTH_CHECKS'] = True


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "public/static"]
MEDIA_ROOT = BASE_DIR / "public/media"





STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'public/static'),   # <-- note the plural 'DIRS' and list syntax
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'public/media')   # separate folder for uploaded media

RAZORPAY_KEY_ID="rzp_test_RAsf0ZEAMpiHyv"
RAZORPAY_KEY_SECRET="Xv3YciSQ8bboV2P4cf0ih0ev"

CRONJOBS = [
    # Run every 5 minutes
    ('*/5 * * * *', 'django.core.management.call_command', ['update_meetings']),
]


# Zoom API credentials
ZOOM_CLIENT_ID = "EB94b09XTC2kfphJJB8cMQ"
ZOOM_CLIENT_SECRET = "a2nC2OCAVtj7QJzr6aGUeUoWI3DPSRya"
ZOOM_ACCOUNT_ID = "J7yp2HtAQLe0aWvhlVSeRg"
ZOOM_EMAIL = "yashmadane06@gmail.com" 




EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_PORT = 465
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='skilllinproj@gmail.com')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='pgzpxzrtxqsvmpdw')



# Production settings (commented out for local development)
# CSRF_TRUSTED_ORIGINS = ["https://skill-link-ptzd.onrender.com"]
# SECURE_HSTS_SECONDS = 31536000

# if not DEBUG:
#     SECURE_SSL_REDIRECT = True
#     SESSION_COOKIE_SECURE = True
#     CSRF_COOKIE_SECURE = True
#     SECURE_HSTS_SECONDS = 31536000
#     SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
#     CSRF_TRUSTED_ORIGINS = ["https://skill-link-ptzd.onrender.com"]


# Development settings
# CSRF_TRUSTED_ORIGINS = ["http://localhost:8000", "http://127.0.0.1:8000", "http://0.0.0.0:8000", "https://skill-link-ptzd.onrender.com"]
# SECURE_HSTS_SECONDS = 0


# SECURE_SSL_REDIRECT = False
# SESSION_COOKIE_SECURE = False
# CSRF_COOKIE_SECURE = False
# SECURE_PROXY_SSL_HEADER = None
# USE_X_FORWARDED_HOST = False



# Use Cloudinary for media storage

# Optional: set MEDIA_URL (Cloudinary handles actual URL)
MEDIA_URL = "/media/"

# At the bottom of settings.py


cloudinary.config(
    cloud_name="dctwxqpeo",
    api_key="948549915113465",
    api_secret="1_L9u37eelt29fTwNyrr99yft4E",
)

DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
